config/routes.rb
Rails.application.routes.draw do

  get 'ru' => 'locale#switch', :code => 'ru'
  get 'en' => 'locale#switch', :code => 'en'

  #account routes
  namespace :account do
    get '/' => '#profile'
    #profile routes
    get 'profile' => :profile
    get 'profile/info' => :get_userinfo
    post 'profile/info' => :save_userinfo
    #security routes
    get 'security' => :security
    post 'security/change_password' => :change_password
    #payment routes
    get 'deposit' => :deposit
    get 'deposit_2btx' => :deposit_2btx
    get 'withdrawal' => :withdrawal
    get 'payment_methods' => :payment_methods
    post 'withdrawal' => :withdrawal_request
  end

  root 'games#index'
  get 'get' => 'games#get'

  get 'top' => 'top#get'
  get 'currencies' => 'currency#get'
  get 'countries' => 'country#get'

  #registration routes
  get 'registration'  => 'registration#index'
  get 'registration/validate' => 'registration#validate'
  get 'register/success' => 'registration#success_registration'
  post 'register' => 'registration#registration'

  #auth routes
  get 'login'  => 'auth#index'
  get 'auth' => 'auth#login'
  get 'logout' => 'auth#logout'
  get 'forgot_password' => 'auth#forgot_password'

  #games routes
  get 'games' => 'games#index'
  get 'games/(:category)' => 'games#index'
  get 'games/get' => 'games#get'
  get 'game/(:id)' => 'game#index'

  #plugin routes
  get 'plugins' => 'plugin#index'
  
  #admin routes
  namespace :admin do
    get 'login/index'
    get 'login/logout'
    get 'login/check_login'
    get 'users/get'
    get 'users/create'
    get 'users/update'
    get 'users/remove'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  before_action :set_locale

  def set_locale
    res = AzartHall::Locale.init(cookies, request, params)
    cookies[:lng] = {value: res}
    if !params[:lng].nil?
      params.delete :lng
      redirect_to url_for(params.except(:lng).merge(only_path: false))
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def root_link()
   return 'http://' + get_domain()
  end
  def get_domain
    Rails.env == 'production' ?  request.host : request.host_with_port
  end
end

app/views/application/_footer.html.erb
<footer>
  <section class="footer-payments">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <ul>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-wm-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-wm.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-yandex-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-yandex.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-qiwi-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-qiwi.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-w1-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-w1.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-skrill-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-skrill.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-megafon-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-megafon.png">
            </a></li>
            <!-- <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-beeline-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-beeline.png">
            </a></li> -->
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-neteller-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-neteller.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-visa-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-visa.png">
            </a></li>
            <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-mastercard-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-mastercard.png">
            </a></li>
            <!-- <li><a href>
              <img class="img-responsive img-shade" src="/images/payments/logo-sc-dis.png">
              <img class="img-responsive img-hover" src="/images/payments/logo-sc.png">
            </a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/application/_leftcol.html.erb
<a><img class="img-responsive img-shade" src="/images/banner-vertical.png"/></a>

app/views/application/_loginform.html.erb
<alert ng-show="alert" type="danger" close="alert=''">{{alert}}</alert>
<alert ng-show="message" type="info" close="message=''">{{message}}</alert>
<form class="form-horizontal login-form" ng-submit="login()">
  <div class="form-group">
    <label for="login" class="col-lg-3 control-label"><%= I18n.t 'frontend.login.login'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-9">
    <% else %>
    <div class="col-lg-8">
    <% end %>
      <input type="text" class="form-control" id="login" placeholder="<%= I18n.t 'frontend.login.login'%>" ng-model="form.login" />
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-lg-3 control-label"><%= I18n.t 'frontend.login.password'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-9">
    <% else %>
    <div class="col-lg-8">
    <% end %>
      <input type="password" class="form-control" id="password" placeholder="<%= I18n.t 'frontend.login.password'%>" ng-model="form.password" />
      <span class="help-block text-center"><a href="#" ng-click="forgotPassword()"><%= I18n.t 'frontend.login.forgot_password'%></a></span>
    </div>
  </div>
  <div class="form-group">
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-9 col-lg-offset-3">
    <% else %>
    <div class="col-lg-8 col-lg-offset-3">
    <% end %>
      <button type="submit" name="button" class="btn btn-green btn-block"><%= I18n.t 'frontend.login.submit'%></button>
    </div>
  </div>
</form>

app/views/application/_loginmodal.html.erb
<script type="text/ng-template" id="loginmodal">
  <div class="modal-header register-header">
    <button type="button" class="close" ng-click="cancel()">&times;</button>
    <h4 class="modal-title"><%= I18n.t 'frontend.menu.login'%></h4>
  </div>
  <div class="modal-body">
    <%= render 'loginform' %>
  </div>
</script>

app/views/application/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" ng-init="navCollapsed = true" ng-click="navCollapsed = !navCollapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%#<a class="navbar-brand btn-default" href="<%= root_link >"><span class="logo">c</span><span class="logo-diamond"><i class="fa fa-diamond"></i></span><span class="logo">sino almaz</span></a>%>
      <a class="navbar-brand btn-default" style="padding: 0" href="<%= root_link %>"><img src="/images/qbit_logo.png" style="height: 100%"/></a>
    </div>

    <div class="collapse navbar-collapse" collapse="navCollapsed">
      <ul class="nav navbar-nav">
          <% if I18n.locale.to_s == 'en' %>
		  <a href="<%= root_link %>?lng=ru" class="btn flag">
                <img src="/images/flags/ru.png"/>
            </a>
          <% else %>
		  <a href="<%= root_link %>?lng=en" class="btn flag">
                <img src="/images/flags/en.png"/>
            </a>
          <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if session[:guid]%>
        <li class="account-info" ng-controller="AccountInfoCtrl">
          <span class="label add-funds"><a href="<%= root_link %><%= account_deposit_path %>">
            <span class="text"><%= I18n.t 'frontend.menu.balance' %>:
            {{user.balance}}   {{user.currency}}</span>
            <span class="btn btn-xs btn-green"><%= I18n.t 'frontend.menu.add_funds' %></span>
            </a></span>
          <span class="btn-group" dropdown is-open="status.isopen">
            <button type="button" class="btn btn-default dropdown-toggle user-button" dropdown-toggle ng-disabled="disabled">
              <a><i class="fa fa-user"></i>&nbsp;   {{user.username}}</a> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="<%= root_link %><%= account_profile_path %>" name="button"><%= I18n.t 'frontend.menu.account.profile' %></a></li>
              <li class="divider"></li>
              <li><a href="<%= root_link %><%= account_deposit_path %>" name="button"><%= I18n.t 'frontend.menu.account.deposit' %></a></li>
              <li><a href="<%= root_link %><%= account_withdrawal_path %>" name="button"><%= I18n.t 'frontend.menu.account.withdraw' %></a></li>
              <li class="divider"></li>
              <li><a href="<%= root_link %>/logout" name="button"><%= I18n.t 'frontend.menu.account.logout' %></a></li>
            </ul>
          </span>
        </li>
      <% else %>
      <li>
        <%= render 'social' %>
      </li>
      <% if !request.original_fullpath.match 'registration' %>
      <li>
        <button type="button" ng-controller="RegisterCtrl" class="btn btn-lg btn-orange" name="button" ng-click="openRegistration()"><%= I18n.t 'frontend.menu.register' %></button>
      </li>
      <li>
        <button type="button" ng-controller="AuthCtrl" class="btn btn-lg btn-green" name="button" ng-click="openAuth()"> <%= I18n.t 'frontend.menu.login' %></button>
      </li>
      <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_registerform.html.erb
<alert ng-show="alert" type="danger" close="alert=''">{{alert}}</alert>
<alert ng-show="message" type="info" close="message=''">{{message}}</alert>
<form class="form-horizontal register-form" ng-submit="register()">
  <div class="form-group">
    <label for="username" class="col-lg-4 control-label"><%= I18n.t 'frontend.register.username'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-5">
    <% else %>
    <div class="col-lg-6">
    <% end %>
        <input type="text" class="form-control" id="username" placeholder="<%= I18n.t 'frontend.register.username'%>" ng-model="form.username" />
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-lg-4 control-label"><%= I18n.t 'frontend.register.email'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-5">
    <% else %>
    <div class="col-lg-6">
    <% end %>
      <input type="text" class="form-control" id="email" placeholder="<%= I18n.t 'frontend.register.email'%>" ng-model="form.email" />
    </div>
  </div>
  <%#<div class="form-group">
    <label for="currency" class="col-lg-4 control-label"><%= I18n.t 'frontend.register.currency'></label>
    <% if !request.original_fullpath.match 'registration' >
    <div class="col-lg-5">
    <% else >
    <div class="col-lg-6">
    <% end >
      <div class="btn-group" dropdown>
        <button type="button" class="btn form-control dropdown-toggle btn-block" dropdown-toggle ng-disabled="disabled">
          {{ currencyText }}  <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="currency">
          <li ng-repeat="cur in currencyList"><a ng-click="chooseCurrency(cur.name, cur.code)">{{cur.name}}</a></li>
        </ul>
      </div>
    </div>
  </div>%>
  <div class="form-group">
    <label for="password" class="col-lg-4 control-label"><%= I18n.t 'frontend.register.password'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-5">
    <% else %>
    <div class="col-lg-6">
    <% end %>
      <input type="password" class="form-control" id="password" placeholder="<%= I18n.t 'frontend.register.password'%>" ng-model="form.password" />
    </div>
  </div>
  <div class="form-group">
    <label for="password" class="col-lg-4 control-label"><%= I18n.t 'frontend.register.confirm_password'%></label>
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-5">
    <% else %>
    <div class="col-lg-6">
    <% end %>
      <input type="password" class="form-control" id="password" placeholder="<%= I18n.t 'frontend.register.confirm_password'%>" ng-model="confirm_password" />
      <div class="checkbox">
        <label>
          <input type="checkbox" ng-model="ageOfConsent"> <span class="checkbox-text"><%= I18n.t 'frontend.register.age'%></span>
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <% if !request.original_fullpath.match 'registration' %>
    <div class="col-lg-5 col-lg-offset-4">
    <% else %>
    <div class="col-lg-6 col-lg-offset-4">
    <% end %>
      <button type="submit" name="button" class="btn btn-block btn-orange submit-button"><%= I18n.t 'frontend.register.submit'%></button>
    </div>
  </div>
</form>

app/views/application/_registermodal.html.erb
<script type="text/ng-template" id="registermodal">

      <div class="modal-header register-header">
        <% if !request.original_fullpath.match 'registration' %>
          <button type="button" class="close" ng-click="cancel()">&times;</button>
        <% end %>
          <h4 class="modal-title"><%= I18n.t 'frontend.menu.register'%></h4>
      </div>
      <div class="modal-body">
        <%= render 'registerform' %>
      </div>
</script>

app/views/application/_reset_passwordform.html.erb
<script type="text/ng-template" id="reset_passwordform">
  <div class="modal-header register-header">
    <button type="button" class="close" ng-click="cancel()">&times;</button>
    <h4 class="modal-title"><%= I18n.t 'frontend.reset_password.title'%></h4>
  </div>
  <div class="modal-body">
    <alert ng-show="alert" type="danger" close="alert=''">{{alert}}</alert>
    <form class="form-horizontal login-form" ng-submit="sendRequest()">
      <div class="form-group">
        <label for="email" class="col-lg-3 control-label"><%= I18n.t 'frontend.reset_password.email'%></label>
        <div class="col-lg-9">
          <input type="text" class="form-control" id="email" placeholder="<%= I18n.t 'frontend.reset_password.email'%>" ng-model="form.email" />
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-9 col-lg-offset-3">
          <button type="submit" name="button" class="btn btn-block btn-green submit-button"><%= I18n.t 'frontend.reset_password.submit'%></button>
        </div>
      </div>
    </form>
  </div>
</script>

app/views/application/_rightcol.html.erb
<div class="panel download-plugin" ng-bg="/images/banner-plugin-<%= I18n.locale %>.jpg">
  <a href="<%= root_link %><%= plugins_path %>" name="button" class="btn btn-lg btn-blue"><%= I18n.t 'frontend.games.download' %></a>
</div>
<% if !request.original_fullpath.match 'registration' %>
<div class="panel">
  <div class="panel-heading">
    <h4 class="panel-title"><%= I18n.t 'frontend.games.top' %></h4>
  </div>
  <div class="panel-body top-players">
    <table class="table table-condensed table-hover">
      <tbody>
        <tr ng-repeat="player in topList">
          <td><i class="fa fa-trophy"></i></td>
          <td>{{player.name}}</td>
          <td><i class="fa fa-money"></i> {{player.won}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/application/_social.html.erb
<!-- <span class="social">
  <a href>
    <img class="img-shade" src="/images/social/google.png">
    <img class="img-hover" src="/images/social/google-hover.png">
  </a>
  <a href>
    <img class="img-shade" src="/images/social/facebook.png">
    <img class="img-hover" src="/images/social/facebook-hover.png">
  </a>
  <a href>
    <img class="img-shade" src="/images/social/vk.png">
    <img class="img-hover" src="/images/social/vk-hover.png">
  </a>
  <a href>
    <img class="img-shade" src="/images/social/mailru.png">
    <img class="img-hover" src="/images/social/mailru-hover.png">
  </a>
  <a href>
    <img class="img-shade" src="/images/social/twitter.png">
    <img class="img-hover" src="/images/social/twitter-hover.png">
  </a>
  <a href>
    <img class="img-shade" src="/images/social/odno.png">
    <img class="img-hover" src="/images/social/odno-hover.png">
  </a>
</span> -->