config/routes.rb
Rails.application.routes.draw do

  get 'ru' => 'locale#switch', :code => 'ru'
  get 'en' => 'locale#switch', :code => 'en'

  #account routes
  namespace :account do
    get '/' => '#profile'
    #profile routes
    get 'profile' => :profile
    get 'profile/info' => :get_userinfo
    post 'profile/info' => :save_userinfo
    #security routes
    get 'security' => :security
    post 'security/change_password' => :change_password
    #payment routes
    get 'deposit' => :deposit
    get 'deposit_2btx' => :deposit_2btx
    get 'withdrawal' => :withdrawal
    get 'payment_methods' => :payment_methods
    post 'withdrawal' => :withdrawal_request
  end

  root 'games#index'
  get 'get' => 'games#get'

  get 'top' => 'top#get'
  get 'currencies' => 'currency#get'
  get 'countries' => 'country#get'

  #registration routes
  get 'registration'  => 'registration#index'
  get 'registration/validate' => 'registration#validate'
  get 'register/success' => 'registration#success_registration'
  post 'register' => 'registration#registration'

  #auth routes
  get 'login'  => 'auth#index'
  get 'auth' => 'auth#login'
  get 'logout' => 'auth#logout'
  get 'forgot_password' => 'auth#forgot_password'

  #games routes
  get 'games' => 'games#index'
  get 'games/(:category)' => 'games#index'
  get 'games/get' => 'games#get'
  get 'game/(:id)' => 'game#index'

  #plugin routes
  get 'plugins' => 'plugin#index'
  
  #admin routes
  namespace :admin do
    get 'login/index'
    get 'login/logout'
    get 'login/check_login'
    get 'users/get'
    get 'users/create'
    get 'users/update'
    get 'users/remove'
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(:file => "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/layouts/account.html.erb
<% content_for :content do %>
  <div class="panel">
    <div class="panel-heading">
      <h4>Account</h4>
    </div>
    <div class="panel-body">
      <div class="col-md-4">
        <div class="list-group">
          <a href="<%= root_link %><%= account_profile_path %>" class="list-group-item">
            <span class="badge"><i class="fa fa-user"></i></span>
            <%= I18n.t 'frontend.menu.account.profile' %>
          </a>
          <a href="<%= root_link %><%= account_security_path %>" class="list-group-item">
            <span class="badge"><i class="fa fa-lock"></i></span>
            <%= I18n.t 'frontend.menu.account.security' %>
          </a>
          <a href="<%= root_link %><%= account_deposit_path %>" class="list-group-item">
            <span class="badge"><i class="fa fa-credit-card"></i></span>
            <%= I18n.t 'frontend.menu.account.deposit' %>
          </a>
          <a href="<%= root_link %><%= account_withdrawal_path %>" class="list-group-item">
            <span class="badge"><i class="fa fa-diamond"></i></span>
            <%= I18n.t 'frontend.menu.account.withdraw' %>
          </a>
        </div>
      </div>
      <div class="col-md-8">
        <%= content_for?(:account_content) ? yield(:account_content) : yield %>
      </div>
    </div>
  </div>
<% end %>
<% parent_layout "application" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Qbit Casino<%= @page_params.title rescue nil %></title>
  <meta name="description" content="<%=@page_params.description rescue nil%>">
  <meta name="Keywords" content="<%=@page_params.keywords rescue nil%>">
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'azarthall', media: 'all' %>
  <%= stylesheet_link_tag params[:controller], media: 'all' %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body ng-app="azarthall">
  <%= render 'menu' %>
  <div class="page-wrapper">
    <% if !request.original_fullpath.match 'game/' %>
    <div class="jumbotron">
      <div class="container">
        <div class="panel">
          <img class="img-responsive" src="/images/banner-<%= I18n.locale %>.jpg" width=""/>
        </div>
      </div>
    </div>
    <% end %>
    <div class="container">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </div>
  <%= render 'footer' %>
  <%= javascript_include_tag 'libs' %>
  <%= javascript_include_tag 'utils' %>
  <%= javascript_include_tag 'account' %>

  <%= render 'loginmodal' %>
  <%= render 'registermodal' %>
  <%= render 'reset_passwordform' %>

  <%= javascript_include_tag params[:controller] %>
  <%= javascript_include_tag("/lang/#{I18n.locale}.js")%>
  <script>
    angular.module('azarthall').constant('lang', '<%= I18n.locale %>');
    angular.module('azarthall.account').constant('accountInfo', {
        guid: '<%=session[:guid]%>',
        username: '<%=session[:username]%>',
        balance: '<%=session[:balance]%>',
        currency: '<%=session[:currency]%>'
    });
  </script>
  <%= yield :constants%>
  <%= yield :js %>

</body>
</html>